import streamlit as st
from datetime import datetime
from agricultural_util import GreenCureAI

st.set_page_config(
    page_title="Green Cure - Crop Recommendation",
    layout="centered",
    initial_sidebar_state="collapsed",
)

with st.sidebar:
    st.title("Green Cure")
    st.markdown("*Crop Recommendation Module*")
    st.markdown("---")
    st.subheader("AI Configuration")
    api_keys = ["GROQ1", "GROQ2", "GROQ3", "GROQ4"]
    selected_api = st.selectbox("Select AI Model", api_keys, index=0)

ai_assistant = None
init_ok = True
try:
    ai_assistant = GreenCureAI(selected_api)
    with st.sidebar:
        st.success(f"AI Model {selected_api} Ready")
except Exception as e:
    init_ok = False
    st.error("Failed to initialize AI. Check .env keys for GROQ_API_KEY_1..4.")
    st.stop()

st.title("Smart Crop Recommendations")
st.caption("AI-powered single-crop recommendation tailored for Indian farming conditions")

with st.form("crop_recommendation_form"):
    st.subheader("Farm Details")
    col1, col2 = st.columns(2)

    with col1:
        location = st.text_input(
            "Location (District, State)",
            placeholder="e.g., Guna, Madhya Pradesh",
            help="Enter district and state for a precise Indian context",
        )
        soil_type = st.selectbox(
            "Soil Type",
            [
                "Black Soil (Regur)",
                "Red Soil",
                "Alluvial Soil",
                "Laterite Soil",
                "Desert Soil",
                "Mountain Soil",
                "Clay",
                "Sandy",
                "Loamy",
            ],
        )

    with col2:
        season = st.selectbox(
            "Season",
            ["Kharif (Monsoon)", "Rabi (Winter)", "Zaid (Summer)"],
        )
        farm_size = st.selectbox(
            "Farm Size",
            [
                "Marginal (< 1 hectare)",
                "Small (1-2 hectares)",
                "Semi-medium (2-4 hectares)",
                "Medium (4-10 hectares)",
                "Large (> 10 hectares)",
            ],
        )

    submitted = st.form_submit_button("Get AI Recommendation", type="primary", use_container_width=True)

if submitted:
    if not location.strip():
        st.error("Please enter your location before requesting a recommendation.")
        st.stop()

    with st.spinner("AI is analyzing your farming conditions..."):
        try:
            rec = ai_assistant.get_crop_recommendation(
                location=location,
                soil_type=soil_type,
                season=season,
                farm_size=farm_size,
            )

            st.success("Recommendation generated successfully!")

            st.markdown("---")
            st.subheader("Recommended Crop")
            st.markdown(f"• Crop: **{rec.crop_name}**")
            colA, colB = st.columns(2)
            with colA:
                st.info(f"Best Planting Season: {rec.planting_season}")
            with colB:
                st.info(f"Expected Yield: {rec.expected_yield}")

            st.success(f"Market Value: {rec.market_value}")

            st.markdown("### Care Instructions")
            for i, tip in enumerate(rec.care_instructions, 1):
                st.markdown(f"{i}. {tip}")

            st.markdown("### Actions")
            report = f"""GREEN CURE - CROP RECOMMENDATION REPORT

Farm Details
- Location: {location}
- Soil Type: {soil_type}
- Season: {season}
- Farm Size: {farm_size}
- Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

RECOMMENDATION
- Crop: {rec.crop_name}
- Planting Season: {rec.planting_season}
- Expected Yield: {rec.expected_yield}
- Market Value: {rec.market_value}

CARE INSTRUCTIONS
""" + "\n".join([f"{i}. {x}" for i, x in enumerate(rec.care_instructions, 1)]) + "\n\nGenerated by Green Cure AI Assistant"

            st.download_button(
                "Download Recommendation",
                data=report,
                file_name=f"crop_recommendation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
                mime="text/plain",
                use_container_width=True,
            )

        except Exception as e:
            st.error(f"Error generating recommendation: {e}")
            st.info("Try different inputs or verify your API key and internet connection.")
